version: '3.8'

services:
  postgres-db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api-gateway:
    build:
      context: ./services/api-gateway
    env_file:
      - ./services/api-gateway/.env
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres-db:5432/mydatabase
    depends_on:
      - postgres-db

  web-ui-server:
    build:
      context: ./services/web-ui/server
    ports:
      - "8080:8080"
    environment:
      - API_GATEWAY_URL=http://api-gateway:8001
    depends_on:
      - api-gateway

  web-ui:
    build:
      context: ./services/web-ui/client
    ports:
      - "5000:5173"
    depends_on:
      - web-ui-server